### ISSUE TITLE
New releases not being published to Deno Land X

### ISSUE THREAD

**Issue by adrianhopebailie** [jozsefsallai/tbl#6]
Maybe the webhook is not setup?

From the instructions:

# Add the webhook

1. Navigate to the repository you want to add.
2. Go to the `Settings` tab.
3. Click on the `Webhooks` tab.
4. Click on the `Add webhook` button.
5. Enter the URL `https://api.deno.land/webhook/gh/tbl` in the payload URL field.
6. Select `application/json` as the content type.
7. Select `Let me select individual events`.
8. Select only the `Branch or tag creation` event.
9. Press `Add webhook`.

**Comment by jozsefsallai** [comment]
tagged a new release! sorry, I could've sworn I had the webhook added. thanks for the heads-up!
